# This is a basic workflow to help you get started with Actions

name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: [self-hosted, linux, X64]

    steps:
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: build and run
        env:
          OLD_SECRET: ${{ secrets.OldSecret }}
          NEW_SECRET: ${{ secrets.NewSecret }}
        run: |
          go build
          nohup ./api "%OLD_SECRET%" "%NEW_SECRET%" &
